version: "3.9"
services:
  exb:
   image: jageagle/esri-exb:exb-1.6
   ports:
       - "3000:3000"
       - "3001:3001"
   volumes:
       - ../widgets:/home/node/ArcGISExperienceBuilder/client/your-extensions/widgets/
       - ../themes:/home/node/ArcGISExperienceBuilder/client/your-extensions/themes/
       - ../public:/home/node/ArcGISExperienceBuilder/server/public/
       - ..:/workspace:cached
   command: npm start